application: red-tide-88204 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  secure: optional

- url: /bootstrap/*
  static_dir: bootstrap
  secure: optional
  
- url: /js
  static_dir: js
  secure: optional
  
- url: /images
  static_dir: images
  secure: optional

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /.*
  script: thesmartcellar.application
  secure: optional

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest